services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: chat_app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chat_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: